### ISSUE TITLE
Mathematical model

### ISSUE THREAD

**Issue by stevielyh** [clussificate/SNDHLP#1]
Hi Kurt,

Thank you for sharing the code.  From the title, I know it is a branch-and-cut approach applied to solve a hub location problem. However, it is hard to know what the model exactly is. I appreciate it if you can also share the mathematical model of the problem. 

Steph

**Comment by clussificate** [comment]
You can find the exact model in this paper.
Branch-and-price-and-cut for a service network design and hub location problem, Ann-Kathrin et. al., 2016, EJOR. 
https://www.sciencedirect.com/science/article/pii/S0377221716303952?via%3Dihub
Hope it helps!

**Comment by stevielyh** [comment]
I got it. Thank you very much!
