### ISSUE TITLE
A detailed example

### ISSUE THREAD

**Issue by Q-max007** [clussificate/SNDHLP#2]
Dear Kurt,
I'm intereseted in the Branch & Price method of this project,could you please share more details of this case and mathamatical model formulations?I'm looking forward to your reply,Thanks a lot.

**Comment by clussificate** [comment]
Yep, you can find more details in this paper: Branch-and-price-and-cut for a service network design and hub
location problem, Rothenbächer , EJOR, 2016.
But note that the implementation is just my homework. 
So the accuracy and completeness cannot be guaranteed. Good luck.

**Comment by Q-max007** [comment]
Thanks for your answer,I'll consider that.
